name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    #Restore Services
    - name: Restore Catalog
      run: dotnet restore src/Services/Catalog/Maktaba.Services.Catalog.Api    
   
    - name: Restore Identiy
      run: dotnet restore src/Services/Identity/Maktaba.Services.Identity.Api   
      
    - name: Restore Order
      run: dotnet restore src/Services/Orders/Maktaba.Services.Ordesr.Api
    
    #Build Services
    - name: Build Catalog
      run: dotnet build src/Services/Catalog/Maktaba.Services.Catalog.Api --no-restore

    - name: Build Identity
      run: dotnet build src/Services/Identity/Maktaba.Services.Identity.Api --no-restore

    - name: Build Order
      run: dotnet build src/Services/Orders/Maktaba.Services.Orders.Api --no-restore
